apiVersion: v1
kind: PersistentVolume
metadata:
  name: test1
  labels:
    name: test1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /exports/test1
    server: ocp36infra2
